### ISSUE TITLE
DTC write back disabled for DTCb

### ISSUE THREAD

**Issue by gurkerlbaron** [renesas/rx-driver-package#20]
In DTC FIT modul the DTC write back is always enabled (in code and commented in documentation). I'm using RX65N with DTCb functionality and regarding to the hardware manual the DTCb allows to disable write back. So why is it always enabled in FIT module?

**Comment by HirokiIshiguro** [comment]
@TatsuyaOgawanx Could you give a comment? Please discuss with your manager internally if you would need.

**Comment by TatsuyaOgawanx** [comment]
@gurkerlbaron 
Sorry for replying late.

DTC writeback always enables in DTCb, because in R_DTC_Create() we want to set the default value of "writeback_disable" is '0' (DTC_WRITEBACK_ENABLE)

If you want to disable write back in DTC FIT module, use R_DTC_Control() after R_DTC_Create().
Woud you see p.42 on DTC FIT manual how to set?
https://www.renesas.com/us/en/document/apn/rx-family-dtc-module-using-firmware-integration-technology-rev390

**Comment by gurkerlbaron** [comment]
Thanks for the information. I will do it that way.
